CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(256) NOT NULL,
    content text NOT NULL,
    author varchar(40) NOT NULL,
    coauthor text,
    category VARCHAR(50),
    created_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)
);

INSERT INTO articles (title, content, author, category) VALUES
(
    'My Life as a Goat',
    'I went to Nepal to live as a goat, and it was much better than being a butler.',
    'E. Blackadder',
    'Artist'
),
(
    'Magnificent Octopus',
    'Once upon a time there was a lovely little sausage.',
    'S. Baldrick',
	'War'
);

ALTER TABLE articles ADD COLUMN available BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE articles ADD COLUMN updated_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000);