# spin_version = "1"
spin_manifest_version = "1"
authors = ["lshoo <lshoo36@gmail.com>"]
description = "Things and thinks about lshoo"
name = "htmx-example"
trigger = { type = "http", base = "/" }
version = "1.0.5"



[[component]]
id = "blog"
source = "api/blog/target/wasm32-wasi/release/blog.wasm"
key_value_stores = ["default"]

[component.trigger]
route = "/api/blog/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api/blog"
watch = ["api/blog/src/**/*.rs", "api/blog/Cargo.toml", "spin.toml"]

[[component]]
id = "timeline"
source = "api/timeline/target/wasm32-wasi/release/timeline.wasm"
key_value_stores = ["default"]

[component.trigger]
route = "/api/timeline/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api/timeline"
watch = ["api/timeline/src/**/*.rs", "api/timeline/Cargo.toml", "spin.toml"]

[[component]]
# source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
source = "modules/spin_static_fs.wasm"
id = "web"
files = [ { source = "web/dist", destination = "/" } ]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
workdir = "web"

# htmx example
# [[component]]
# id = "htmx-example"
# source = "target/wasm32-wasi/release/htmx_example.wasm"
# allowed_http_hosts = ["0.0.0.0:8000"]
# [component.trigger]
# # route = "/..."
# route = "/htmx"
# [component.build]
# command = "cargo build --target wasm32-wasi --release"
# watch = ["src/**/*.rs", "Cargo.toml"]


# [[component]]
# id = "clicked"
# source = "htmx/clicked/target/wasm32-wasi/release/clicked.wasm"
# allowed_http_hosts = []
# [component.trigger]
# route = "/htmx/clicked"
# [component.build]
# command = "cargo build --target wasm32-wasi --release"
# workdir = "htmx/clicked"
# watch = ["src/**/*.rs", "Cargo.toml"]

# [[component]]
# id = "gohome"
# source = "/htmx/gohome/target/wasm32-wasi/release/go_home.wasm"
# allowed_http_hosts = []
# [component.trigger]
# route = "/htmx/gohome"
# [component.build]
# command = "cargo build --target wasm32-wasi --release"
# workdir = "htmx/gohome"
# watch = ["src/**/*.rs", "Cargo.toml"]