spin_version = "1"
authors = ["lshoo <lshoo36@gmail.com>"]
description = "Things and thinks about lshoo"
name = "lshoo"
trigger = { type = "http", base = "/" }
version = "1.0.5"

[[component]]
id = "spaces"
source = "api/blog/target/wasm32-wasi/release/spaces.wasm"
key_value_stores = ["default"]

[component.trigger]
route = "/api/blog/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api/blog"
watch = ["api/blog/src/**/*.rs", "api/blog/Cargo.toml", "spin.toml"]

